### ISSUE TITLE
Cambiare il carattere di inizio del comando

### ISSUE THREAD

**Issue by ArmeF97** [fen0x/marvin#12]
Attualmente il carattere iniziale è '/'
esempio: /postlink

Sfortunatamente, quello è il carattere dei veri comandi di telegram. Il bot che usiamo per moderare il gruppo, ha la possibilità di cancellare all'istante i comandi che non riconosce. Ovviamente /postlink non lo riconosce. 
Questa funzionalità è molto comoda, e non bisogna perderla. Il bot admin è talmente veloce che cancella /postlink prima che possa essere visto dal bot marvin. 

Per ora, ho spento la cancellazione dei comandi.

Tuttavia, con questa segnalazione, diciamo anche che possiamo considerarla un mezzo bug, chiedo di scegliere un nuovo carattere.

Suggerisco qualcosa come

+postlink
-postlink
=postlink
$postlink
&postlink
%postlink

ecc...

Sono sicuro che questi il bot li cancella  
/ ! # .
Slash, punto esclamativo, cancelletto, punto

Discutiamo insieme su quale carattere è giusto scegliere (ovviamente va bene anche un altro rispetto a quelli che ho proposto io)

**Comment by timendum** [comment]
Non penso sia possibile, telegram invoca il bot solo a fronte di un comando, che appunto deve iniziare per `/`. (vedi CommandHandler master/marvin.py#L288 )

Anzi, andrebbe registrato il comando su BotFather.

**Comment by ArmeF97** [comment]
Invece è possibile, io so tutto di telegram. Bisogna impostare su botfather che marvin ha accesso a tutti i messaggi

**Comment by timendum** [comment]
> io so tutto di telegram

ok....

Commenti a parte, utilizzare i comandi mi sembra la cosa più giusta, meno esosa per il server e più user-friendly. Si può farlo diversamente, ma piuttosto sistemerei il bot che cancella i comandi che non capisce.

**Comment by fen0x** [comment]
> piuttosto sistemerei il bot che cancella i comandi che non capisce.

In effetti sarei anche io per questa soluzione, visto che lo / è il modo standard di passare comandi ad un bot.

Non è possibile escludere determinati comandi dalle grinfie del tuo bot?

**Comment by ArmeF97** [comment]
Il bot admin non è sviluppato da noi. 
Non credo ci sia altra soluzione rispetto a quella che ho proposto, per non rinunciare alla comoda funzione di cancellazioni comandi

**Comment by ArmeF97** [comment]
Non lo fa. È un difetto del bot che usiamo su cui, ripeto, non abbiamo controllo

**Comment by fen0x** [comment]
Scrivere allo sviluppatore?

**Comment by ArmeF97** [comment]
Accetta modifiche, a pagamento

**Comment by fen0x** [comment]
Non è una modifca, come dicevi tu stesso è un bug.

**Comment by ArmeF97** [comment]
Ci ho già provato altre volte con cose più gravi, la risposta è quella

**Comment by fen0x** [comment]
Forse che abbiamo il bot sbagliato nel gruppo?

**Comment by ArmeF97** [comment]
In che senso? Se conosci un bot admin migliore dell'attuale, consiglialo pure

**Comment by fen0x** [comment]
Uno qualsiasi che consenta di utilizzare altri bot che usano comandi standard che iniziano con lo /.

**Comment by ArmeF97** [comment]
E che faccia tutte le cose che fa il nostro bot admin, se lo trovi scrivilo pure 

Io non ne conosco

**Comment by edmael** [comment]
> Invece è possibile, io so tutto di telegram. Bisogna impostare su botfather che marvin ha accesso a tutti i messaggi

Purtroppo non credo sia possibile passare comandi con un carattere diverso da /.
"A command must always start with the ‘/’ symbol and may not be longer than 32 characters. Commands can use latin letters, numbers and underscores." (tratto da qui: https://core.telegram.org/bots)

Quale bot viene utilizzato nel gruppo?
Quali funzionalità sono realmente necessarie che rendono necessario il suo utilizzo?

**Comment by ArmeF97** [comment]
> Purtroppo non credo sia possibile passare comandi con un carattere diverso da /.

Questo discorso vale solo se si imposta da botfather la lettura dei messaggi riservati al solo bot, invece se si imposta la possibilità di avere accesso a tutti i messaggi, è lui che può decidere di triggerarsi quando legge ciò che vuole, visto che li legge tutti

> Quale bot viene utilizzato nel gruppo?
> Quali funzionalità sono realmente necessarie che rendono necessario il suo utilizzo?

Un clone di grouphelp, domani scrivo una lista di tutte le funzionalità che stiamo usando

**Comment by gbalduzzi** [comment]
@edmael i bot possono essere impostati su due modalità:
- Legge solo i messaggi che rappresentano comandi, ovvero quelli che iniziano per /
- Legge tutti i messaggi (vedi per esempio spacobot)

Quindi puoi impostare il bot sulla lettura di TUTTI i messaggi, e poi via codice puoi riconoscere la sequenza di caratteri che preferisci. 

Detto questo, trovo comunque stupido che ci sia un bot che impedisce l'esistenza di altri bot senza possibilità di blacklist o altro.

**Comment by ArmeF97** [comment]
> Detto questo, trovo comunque stupido che ci sia un bot che impedisce l'esistenza di altri bot senza possibilità di blacklist o altro.

Anche io, ma è il meglio che esiste. La soluzione migliore sarebbe che ci scriviamo noi anche il bot admin, perché io non conosco bot che facciano tutto quello che fa questo

**Comment by ArmeF97** [comment]
Visto che l'errore è del bot admin, chiudiamo questo issue
