### ISSUE TITLE
Scrivere chi ha eseguito una certa azione nel messaggio di risposta del bot

### ISSUE THREAD

**Issue by ldeluigi** [fen0x/marvin#18]
esempio:
Delooo, Il tuo commento è stato aggiunto al post!

**Comment by ArmeF97** [comment]
E forse valuterei di aggiungerci anche il link al commento appena inviato, sempre nel messaggio del bot

**Comment by ScrappyCocco** [comment]
Fatto nell'ultimo commit, controllate se trovate inesattezze
