### ISSUE TITLE
Filtrare (al meglio delle possibilità) i messaggi con contenuti discutibili postati da telegram a reddit

### ISSUE THREAD

**Issue by ldeluigi** [fen0x/marvin#19]

**Comment by ArmeF97** [comment]
Suggerisco una lista di parole bandite. Nel caso il messaggio ne contenga, il bot risponderà nel gruppo telegram dicendo "Non posso postare perché contiene parole bandite"

**Comment by ArmeF97** [comment]
Però anche un filtro in più non guasterebbe, ridurrebbe il carico dei mod

**Comment by ScrappyCocco** [comment]
Quindi filtro sì o filtro no?
Ricordiamo che un filtro è facilmente bypassabile, se io scrivo una parolaccia con un 1 invece di una i questa già non viene riconosciuta

**Comment by ArmeF97** [comment]
Io direi filtro sì, ma non come priorità. Questa è l'ultima cosa da implementare. Aiuterà quel poco, ok è aggirabile, ma qualcosina fa. Qualcosina è meglio di niente. 
Ripeto, da fare, ma come ultima, priorità al resto

**Comment by fen0x** [comment]
Sì, se proprio vogliamo implementare una roba del genere, teniamola a bassissima priorità.

**Comment by ArmeF97** [comment]
Forse questo può aiutare 
https://github.com/ArmeF97/marvin/commit/f8dc4093c8cfad3952c76987cc1beff36b73f6e0

**Comment by Defkon1** [comment]
Aggiunto un piccolo ehnancement alla lista: https://github.com/fen0x/marvin/pull/72
