### ISSUE TITLE
Aggiungere il link (telegram) del testo da cui proviene il post (su reddit) e altre cosette

### ISSUE THREAD

**Issue by ArmeF97** [fen0x/marvin#20]
Se io scrivo "ciao" su telegram, e qualcuno ci fa /posttext, esso viene pubblicato
Il post su reddit conterrà "ciao".

Io invece propongo di aggiungere, sul fondo, una dicitura del tipo
"questo post proviene da telegram grazie al bot marvin"
dove
- la parola "telegram" sarà un link diretto al messaggio dal gruppo telegram https://t.me/ItalyInformatica/1234 (dove 1234 è il numero [message_id] del messaggio postato)
- la parola "marvin" avrà un link a questa repo di github

**Comment by ScrappyCocco** [comment]
Esiste già, [come in postlink c'è il commento di default](https://github.com/fen0x/marvin/blob/master/marvin.py#L254)

**Comment by ArmeF97** [comment]
Però nel test che ho visto di fen0x di oggi, non c'era nessun commento. Quelli reddit dovrebbe conservarli
https://www.reddit.com/r/ItalyInformatica/comments/al1zyy/testbot/

**Comment by ScrappyCocco** [comment]
Invece appare, forse ha cancellato il post troppo in fretta e non è apparso il commento, in ogni caso come vedi dal codice, c'è.

![cattura](https://user-images.githubusercontent.com/11294898/51927763-9d538680-23f4-11e9-8804-03314a033e70.PNG)

**Comment by ArmeF97** [comment]
Ora il commento è comparso
https://www.reddit.com/r/ItalyInformatica/comments/al2edh/telegram_delooo_provissima/
