### ISSUE TITLE
Post nel gruppo telegram degli issue (o pr) aperti su questa repo

### ISSUE THREAD

**Issue by ArmeF97** [fen0x/marvin#21]
Se qualcuno apre una issue (o una pr) su questa repo, sarebbe carino si inviasse un messaggio nel gruppo telegram, di modo da renderne partecipi tutti

**Comment by ScrappyCocco** [comment]
Questo non è compito di questo bot che collega reddit a telegram, inoltre si genererebbe troppo spam, servirebbe un altro canale per queste notifiche

**Comment by ArmeF97** [comment]
Vediamo cosa dice fen0x, questa era solo un'idea, non è fondamentale come cosa.
Sicuramente separarlo in un altro canale perderebbe di senso, perché altrimenti il canale separato può tranquillamente essere quello già esistente: le notifiche di github 😆

**Comment by fen0x** [comment]
Boh, chi segue questo progetto può avere le comode notifiche delle issue in mail. Non mi pare che aggiungere una notifica su telegram porti qualche vantaggio sostanziale.

**Comment by ArmeF97** [comment]
Era per coinvolgere più persone nel progetto, ma va benissimo anche così
