### ISSUE TITLE
Comando /delrule [numero]

### ISSUE THREAD

**Issue by ArmeF97** [fen0x/marvin#25]
Rispondendo ad link postato dal bot (quindi un post del subreddit postato direttamente da reddit) con il comando, ad esempio /delrule 1, il bot commenta che viola la regola 1 (e magari scrive anche la regola (vedi commento d'esempio https://www.reddit.com/r/ItalyInformatica/comments/al305w/semplice_crm_per_consulente/efa79k6/), il bot poi cancella il post, e elimina anche il comando /delrule del gruppo e il post sul gruppo telegram al quale si aveva risposto con /delrule. Il bot blocca anche i commenti al post di reddit appena cancellato (su questo non saprei, deciderà fen0x)

Spero di essermi spiegato bene.
Sostanzialmente riduce molto lavoro a fen0x

**Comment by ScrappyCocco** [comment]
Credo sia facilmente fattibile con un JSON, mi piace

**Comment by ScrappyCocco** [comment]
Fatto, [controllate se il codice vi sembra corretto](https://github.com/fen0x/marvin/blob/759942a812ab8bc84ca5948019b5e1271e0b450d/marvin.py#L273)
