### ISSUE TITLE
/comment permette di commentare anche i post cancellati

### ISSUE THREAD

**Issue by ArmeF97** [fen0x/marvin#28]
![immagine](https://user-images.githubusercontent.com/6240983/52012823-ddd9ff80-24db-11e9-9744-02b2a4073c4c.png)

Come si può vedere, seppure l'app slide (client non ufficiale di reddit) mi dice che non potrei commentare, e non me lo fa fare, il bot lo può fare e quindi da telegram si bypassa il limite di reddit

**Comment by ScrappyCocco** [comment]
Al momento sì, lo so, [è fixato nella nuova versione](https://github.com/fen0x/marvin/blob/version_3/marvin.py#L168)
