### ISSUE TITLE
Quando viene postato un video youtube con /postlink, il titolo del post è "Youtube" e non il titolo del video

### ISSUE THREAD

**Issue by fen0x** [fen0x/marvin#30]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/1822818/52113012-6fdf2680-2608-11e9-8b64-c59edf73be1b.png">

**Comment by ArmeF97** [comment]
Parli in telegram? Perché io non vedo titoli dei post su telegram, ma solo messaggi, e l'unica scritta su cui hai controllo è "post creato: link"
Quel grassetto sotto è l'anteprima che telegram genera, possiamo solo scegliere se attivarla o meno. Ma se la attivi, è quella

**Comment by ScrappyCocco** [comment]
No @ArmeF97 sta parlando di [questo post qui](https://www.reddit.com/comments/am0617) creato tramite telegram, che ha come titolo solo "Youtube"

**Comment by fen0x** [comment]
Se nel sorgente della pagina non è proprio presente il titolo del video, amen, non si risolve. Altrimenti potrasti prenderti il campo condizionatamente al fatto che il sito sia youtube.

**Comment by ScrappyCocco** [comment]
Bisognerebbe usare [queste API di Youtube](https://developers.google.com/youtube/v3/docs/videos/list) quando il link è di youtube, vedi tu se ne vale la pena, alla fine è solo una richiesta da fare con una api-key suppongo

**Comment by fen0x** [comment]
Direi che il video che passa sul gruppo telegram non è una casistica rara e postare con titolo Youtube porterebbe a rimpire il subreddit con post con lo stesso identico titolo.
