### ISSUE TITLE
Aggiungere comando /postphoto e /postvideo (o unico, /postmedia)

### ISSUE THREAD

**Issue by zarEclEC** [fen0x/marvin#38]
Come /posttext e /postlink, ma pubblica una foto o un video
Forse potrebbe essere /postmedia e non /postphoto e /postivideo separati, se video e photo funzionano uguali (bisogna vedere l'implementazione delle librerie)

**Comment by ScrappyCocco** [comment]
Credo che vadano letti con [photo](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.photo) e [video](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.video), scaricati in locale e quindi ri-uploadati su reddit (con le api di reddit), darò un'occhiata
