### ISSUE TITLE
Precedenza al controllo se moderatore 

### ISSUE THREAD

**Issue by fen0x** [fen0x/marvin#43]
Nel controllo se un comando può essere eseguito, andrebbe data la precedenza a quello se un utente è moderatore. Altrimenti gli utenti si prendono messaggi di errore che, da un punto di vista formale, non sono corretti.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/1822818/52493530-fc22b800-2bcb-11e9-8439-46a3027be4cd.png">
In questo caso il bot avrebbe dovuto rispondere che non è moderatore e non che deve rispondere ad un messaggio.

**Comment by ArmeF97** [comment]
Faccio io, tra un po' mando una pr

**Comment by ArmeF97** [comment]
fatto in https://github.com/fen0x/marvin/pull/46
