### ISSUE TITLE
Aggiungere un comando che approvi un post sul subreddit

### ISSUE THREAD

**Issue by fen0x** [fen0x/marvin#47]
Al contrario di /delrule,  questo comando dovrebbe, in risposta ad un link sul subreddit, approvare il post e aggiungere un tag fra quelli disponibili nel sub.

Un esempio di sintassi potrebbe essere:
`/approve programmazione`

**Comment by ScrappyCocco** [comment]
[SubredditFlair](https://praw.readthedocs.io/en/latest/code_overview/other/subredditflair.html?highlight=flair) per qualche motivo non ritorna i flair del subreddit di test, trovati quelli il comando ci vuole poco a farlo
