### ISSUE TITLE
Disponibilità per tutti dei comandi /postlink e /posttext

### ISSUE THREAD

**Issue by fen0x** [fen0x/marvin#49]
Alla fine non credo che ci sarebbero grandi abusi e comunque si possono sempre moderare.

**Comment by ScrappyCocco** [comment]
Fixato in [https://github.com/fen0x/marvin/commit/c05143daadb8c5dbcb9479a14d9d3c81ad3fe8b1](https://github.com/fen0x/marvin/commit/c05143daadb8c5dbcb9479a14d9d3c81ad3fe8b1)
