### ISSUE TITLE
Aggiungere un parametro nel comando postlink per inserire nel titolo anche un tag per la lingua

### ISSUE THREAD

**Issue by fen0x** [fen0x/marvin#50]
Come da best practice per il posting sul subreddit, se il link è in inglese sarebbe buona norma inserire nel titolo un tag [ENG].
https://www.reddit.com/r/ItalyInformatica/wiki/guidelines

**Comment by ScrappyCocco** [comment]
Fatto anche questo in [https://github.com/fen0x/marvin/commit/c05143daadb8c5dbcb9479a14d9d3c81ad3fe8b1](https://github.com/fen0x/marvin/commit/c05143daadb8c5dbcb9479a14d9d3c81ad3fe8b1)
