### ISSUE TITLE
Modifica dei commenti

### ISSUE THREAD

**Issue by ldeluigi** [fen0x/marvin#54]
Possibilità di modificare un commento postato dal gruppo al subreddit

**Comment by ScrappyCocco** [comment]
Come la faresti?
Non è facile capire che commento modificare, credo che il modo più semplice sia rispondere al messaggio contenente il link postato con il nuovo testo del commento
Modificare il messaggio con /comment è fattibile ma bisognerebbe cercare l'id del commento su reddit
