### ISSUE TITLE
Eliminare il messaggio di cancellazione del post (o girarlo solo sul gruppo di controllo)

### ISSUE THREAD

**Issue by fen0x** [fen0x/marvin#55]
A seguito del comando /delrule, il bot dovrebbe evitare di avvisare sul gruppo principale che il post è stato eliminato. Per logging, potrebbe comunque farlo sul gruppo di controllo dei mod.

**Comment by ScrappyCocco** [comment]
Fatto in [https://github.com/fen0x/marvin/commit/db644686fae8bb4cebbbb587c7a2f2df06ba02e4](https://github.com/fen0x/marvin/commit/db644686fae8bb4cebbbb587c7a2f2df06ba02e4)
