### ISSUE TITLE
Post in formato testo

### ISSUE THREAD

**Issue by fen0x** [fen0x/marvin#7]
Nel caso il messaggio su cui si fa la richiesta non contenga un link, il bot deve richiedere un titolo e sottometterà al sub un post in formato testuale

**Comment by ScrappyCocco** [comment]
Questo è ancora un problema per il titolo, come dicevo il metodo migliore sarebbe rispondere ad un messaggio con
`/posttext <title>`

**Comment by ScrappyCocco** [comment]
Finito [in questo commit](https://github.com/fen0x/marvin/commit/1f21520fb1a70126ae96832e141f59f844190a0d)
