### ISSUE TITLE
Il nome utente riportato dovrebbe essere quello dell'autore

### ISSUE THREAD

**Issue by fen0x** [fen0x/marvin#9]
Nel post sul subreddit viene riportato il nome utente di chi ha dato il comando e non quello dell'utente che ha creato il messaggio contenente il link

**Comment by ScrappyCocco** [comment]
Sì lo so, credevo fosse corretto per qualche motivo, bisogna mettere il nome del messaggio originale?

**Comment by fen0x** [comment]
Esatto, così l'autore si vede riconosciuto il proprio contributo.

**Comment by fen0x** [comment]
Dovrebbe essere a posto. Controllate perfavore.

**Comment by ScrappyCocco** [comment]
Correzione confermata [link al merge](https://github.com/fen0x/marvin/pull/13)
